return {
  version = "1.1",
  luaversion = "5.1",
  orientation = "orthogonal",
  width = 10,
  height = 16,
  tilewidth = 16,
  tileheight = 16,
  properties = {},
  tilesets = {
    {
      name = "tiles",
      firstgid = 1,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      image = "tiles.png",
      imagewidth = 16,
      imageheight = 208,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      tiles = {}
    }
  },
  layers = {
    {
      type = "objectgroup",
      name = "Objects",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 224,
          width = 0,
          height = 0,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 192,
          width = 0,
          height = 0,
          rotation = 0,
          gid = 9,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 224,
          width = 0,
          height = 0,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 160,
          width = 0,
          height = 0,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 160,
          width = 0,
          height = 0,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 160,
          width = 0,
          height = 0,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 160,
          width = 0,
          height = 0,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 160,
          width = 0,
          height = 0,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 112,
          width = 0,
          height = 0,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 112,
          width = 0,
          height = 0,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 96,
          width = 0,
          height = 0,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 96,
          width = 0,
          height = 0,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 160,
          width = 0,
          height = 0,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 80,
          width = 0,
          height = 0,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 80,
          width = 0,
          height = 0,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 80,
          width = 0,
          height = 0,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 80,
          width = 0,
          height = 0,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
